-- 005: FanCore hygiene + failure intelligence.
--
-- fancore_capacity: per-model snapshots of FanCore's Bulk Posting tab counts. FanCore silently
-- drops new bulk posts once a model's record count exceeds its ~1000-record window (discovered
-- 06.07.2026 — 4 models bricked by ~900+ June-era failed records each). The capacity watchdog
-- cron snapshots counts daily and auto-cleans Failed records when all_count >= soft limit.
--
-- video_jobs failure columns: classify posting failures (failure_kind), auto-remediate known
-- kinds, and flag unrecoverable jobs for review in the FanslyTrends UI (needs_review + diagnosis).

CREATE TABLE IF NOT EXISTS fancore_capacity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id integer,                -- trends_models.model_number (matches scheduled_posts convention)
  all_count integer NOT NULL,
  scheduled_count integer NOT NULL,
  sent_count integer NOT NULL,
  failed_count integer NOT NULL,
  captured_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS fancore_capacity_model_time ON fancore_capacity (model_id, captured_at DESC);

ALTER TABLE video_jobs ADD COLUMN IF NOT EXISTS failure_kind text;
ALTER TABLE video_jobs ADD COLUMN IF NOT EXISTS needs_review boolean NOT NULL DEFAULT false;
ALTER TABLE video_jobs ADD COLUMN IF NOT EXISTS diagnosis text;

-- ROLLBACK: DROP TABLE fancore_capacity; ALTER TABLE video_jobs DROP COLUMN failure_kind,
--           DROP COLUMN needs_review, DROP COLUMN diagnosis;  (all additive/nullable — safe to leave)
