-- 008: Wave C — FYP analytics feed + repost automation.
--
-- fyp_media_stats: nightly snapshots of FanCore's FYP Analytics → Media tab per model
-- (model_id = trends_models.model_number convention). Feeds the weekly repost picker;
-- no analytics UI (FanCore already has one — user decision).
--
-- repost_ledger: which media were reposted when → enforces the 14-day per-media cooldown
-- ("repost at least once every 2–3 weeks").
--
-- video_jobs repost columns: repost jobs carry a preset output_r2_key (downloaded from
-- FanCore + watermark-cropped) and skip rendering entirely (inserted as 'approved').

CREATE TABLE IF NOT EXISTS fyp_media_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id integer NOT NULL,
  media_id text NOT NULL,
  fyp_views integer NOT NULL DEFAULT 0,
  direct_views integer NOT NULL DEFAULT 0,
  engagement numeric,
  avg_watch_sec numeric,
  fancore_score numeric,
  duration_sec numeric,
  captured_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS fyp_media_stats_lookup ON fyp_media_stats (model_id, media_id, captured_at DESC);

CREATE TABLE IF NOT EXISTS repost_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id integer NOT NULL,
  media_id text NOT NULL,
  reposted_at timestamptz NOT NULL DEFAULT now(),
  job_id uuid
);
CREATE INDEX IF NOT EXISTS repost_ledger_lookup ON repost_ledger (model_id, media_id, reposted_at DESC);

ALTER TABLE video_jobs ADD COLUMN IF NOT EXISTS is_repost boolean NOT NULL DEFAULT false;
ALTER TABLE video_jobs ADD COLUMN IF NOT EXISTS source_media_id text;

-- ROLLBACK: DROP TABLE fyp_media_stats; DROP TABLE repost_ledger;
--           ALTER TABLE video_jobs DROP COLUMN is_repost, DROP COLUMN source_media_id;
-- post_id nullable: repost jobs have no source trends_post (Wave C)
ALTER TABLE video_jobs ALTER COLUMN post_id DROP NOT NULL;
